#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
$app = new Symfony\Component\Console\Application('October CMS Bootstrapper', '0.0.1');
$app->add(new \OFFLINE\Bootstrapper\October\Console\InitCommand);
$app->add(new \OFFLINE\Bootstrapper\October\Console\InstallCommand);
$app->run();